language: java
before_script:
- echo "Starting building"
script:
- mvn clean package
after_script:
- echo "Script finished"
after_success:
- echo "Build ready"
- ls -l $TRAVISE_BUILD_DIR/GrishchenkoIS/IS_project25/laba4/target
after_failure
- echo "Build failure"
